before_script:
  - export COMPOSE_PROJECT_NAME=buildpipeline_${CI_PIPELINE_ID}
  
build:
  script:
    - docker-compose run --rm composer install --prefer-dist -o
    - docker-compose build eucliid

test:
  script:
    - docker-compose run --rm eucliid
    - docker-compose run --rm eucliid help

deploy:
  script:
    - docker-compose push
