version: '2'
services:

  composer:
    image: composer
    volumes:
      # Mount application
      - ./app:/app
      # Mount external build folder, which will be COPYied to the Docker image
      - ./vendor-build:/app/vendor

  eucliid:
    build: .
    image: ${PHP_IMAGE}
